// Code generated by MockGen. DO NOT EDIT.
// Source: event_dispatcher.go

// Package signalwire is a generated GoMock package.
package signalwire

import (
	context "context"
	json "encoding/json"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIEventCalling is a mock of IEventCalling interface
type MockIEventCalling struct {
	ctrl     *gomock.Controller
	recorder *MockIEventCallingMockRecorder
}

// MockIEventCallingMockRecorder is the mock recorder for MockIEventCalling
type MockIEventCallingMockRecorder struct {
	mock *MockIEventCalling
}

// NewMockIEventCalling creates a new mock instance
func NewMockIEventCalling(ctrl *gomock.Controller) *MockIEventCalling {
	mock := &MockIEventCalling{ctrl: ctrl}
	mock.recorder = &MockIEventCallingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEventCalling) EXPECT() *MockIEventCallingMockRecorder {
	return m.recorder
}

// callConnectStateFromStr mocks base method
func (m *MockIEventCalling) callConnectStateFromStr(s string) (CallConnectState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callConnectStateFromStr", s)
	ret0, _ := ret[0].(CallConnectState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callConnectStateFromStr indicates an expected call of callConnectStateFromStr
func (mr *MockIEventCallingMockRecorder) callConnectStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callConnectStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callConnectStateFromStr), s)
}

// callStateFromStr mocks base method
func (m *MockIEventCalling) callStateFromStr(s string) (CallState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callStateFromStr", s)
	ret0, _ := ret[0].(CallState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callStateFromStr indicates an expected call of callStateFromStr
func (mr *MockIEventCallingMockRecorder) callStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callStateFromStr), s)
}

// callPlayStateFromStr mocks base method
func (m *MockIEventCalling) callPlayStateFromStr(s string) (PlayState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callPlayStateFromStr", s)
	ret0, _ := ret[0].(PlayState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callPlayStateFromStr indicates an expected call of callPlayStateFromStr
func (mr *MockIEventCallingMockRecorder) callPlayStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callPlayStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callPlayStateFromStr), s)
}

// callRecordStateFromStr mocks base method
func (m *MockIEventCalling) callRecordStateFromStr(s string) (RecordState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callRecordStateFromStr", s)
	ret0, _ := ret[0].(RecordState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callRecordStateFromStr indicates an expected call of callRecordStateFromStr
func (mr *MockIEventCallingMockRecorder) callRecordStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callRecordStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callRecordStateFromStr), s)
}

// callDetectEventFromStr mocks base method
func (m *MockIEventCalling) callDetectEventFromStr(event, detType string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callDetectEventFromStr", event, detType)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callDetectEventFromStr indicates an expected call of callDetectEventFromStr
func (mr *MockIEventCallingMockRecorder) callDetectEventFromStr(event, detType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callDetectEventFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callDetectEventFromStr), event, detType)
}

// callFaxEventFromStr mocks base method
func (m *MockIEventCalling) callFaxEventFromStr(t string) (FaxEventType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callFaxEventFromStr", t)
	ret0, _ := ret[0].(FaxEventType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callFaxEventFromStr indicates an expected call of callFaxEventFromStr
func (mr *MockIEventCallingMockRecorder) callFaxEventFromStr(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callFaxEventFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callFaxEventFromStr), t)
}

// callDisconnectReasonFromStr mocks base method
func (m *MockIEventCalling) callDisconnectReasonFromStr(r string) (CallDisconnectReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callDisconnectReasonFromStr", r)
	ret0, _ := ret[0].(CallDisconnectReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callDisconnectReasonFromStr indicates an expected call of callDisconnectReasonFromStr
func (mr *MockIEventCallingMockRecorder) callDisconnectReasonFromStr(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callDisconnectReasonFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callDisconnectReasonFromStr), r)
}

// callTapStateFromStr mocks base method
func (m *MockIEventCalling) callTapStateFromStr(s string) (TapState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callTapStateFromStr", s)
	ret0, _ := ret[0].(TapState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callTapStateFromStr indicates an expected call of callTapStateFromStr
func (mr *MockIEventCallingMockRecorder) callTapStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callTapStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callTapStateFromStr), s)
}

// callSendDigitsStateFromStr mocks base method
func (m *MockIEventCalling) callSendDigitsStateFromStr(s string) (SendDigitsState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callSendDigitsStateFromStr", s)
	ret0, _ := ret[0].(SendDigitsState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callSendDigitsStateFromStr indicates an expected call of callSendDigitsStateFromStr
func (mr *MockIEventCallingMockRecorder) callSendDigitsStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callSendDigitsStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callSendDigitsStateFromStr), s)
}

// callDirectionFromStr mocks base method
func (m *MockIEventCalling) callDirectionFromStr(s string) (CallDirection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callDirectionFromStr", s)
	ret0, _ := ret[0].(CallDirection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callDirectionFromStr indicates an expected call of callDirectionFromStr
func (mr *MockIEventCallingMockRecorder) callDirectionFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callDirectionFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callDirectionFromStr), s)
}

// callPlayAndCollectStateFromStr mocks base method
func (m *MockIEventCalling) callPlayAndCollectStateFromStr(s string) (CollectResultType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callPlayAndCollectStateFromStr", s)
	ret0, _ := ret[0].(CollectResultType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callPlayAndCollectStateFromStr indicates an expected call of callPlayAndCollectStateFromStr
func (mr *MockIEventCallingMockRecorder) callPlayAndCollectStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callPlayAndCollectStateFromStr", reflect.TypeOf((*MockIEventCalling)(nil).callPlayAndCollectStateFromStr), s)
}

// dispatchStateNotif mocks base method
func (m *MockIEventCalling) dispatchStateNotif(ctx context.Context, callParams CallParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchStateNotif", ctx, callParams)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchStateNotif indicates an expected call of dispatchStateNotif
func (mr *MockIEventCallingMockRecorder) dispatchStateNotif(ctx, callParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchStateNotif", reflect.TypeOf((*MockIEventCalling)(nil).dispatchStateNotif), ctx, callParams)
}

// dispatchConnectStateNotif mocks base method
func (m *MockIEventCalling) dispatchConnectStateNotif(ctx context.Context, callParams CallParams, peer PeerDeviceStruct, ccstate CallConnectState, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchConnectStateNotif", ctx, callParams, peer, ccstate, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchConnectStateNotif indicates an expected call of dispatchConnectStateNotif
func (mr *MockIEventCallingMockRecorder) dispatchConnectStateNotif(ctx, callParams, peer, ccstate, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchConnectStateNotif", reflect.TypeOf((*MockIEventCalling)(nil).dispatchConnectStateNotif), ctx, callParams, peer, ccstate, rawEvent)
}

// dispatchPlayState mocks base method
func (m *MockIEventCalling) dispatchPlayState(ctx context.Context, callID, ctrlID string, playState PlayState, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchPlayState", ctx, callID, ctrlID, playState, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchPlayState indicates an expected call of dispatchPlayState
func (mr *MockIEventCallingMockRecorder) dispatchPlayState(ctx, callID, ctrlID, playState, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchPlayState", reflect.TypeOf((*MockIEventCalling)(nil).dispatchPlayState), ctx, callID, ctrlID, playState, rawEvent)
}

// dispatchRecordState mocks base method
func (m *MockIEventCalling) dispatchRecordState(ctx context.Context, callID, ctrlID string, recordState RecordState, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchRecordState", ctx, callID, ctrlID, recordState, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchRecordState indicates an expected call of dispatchRecordState
func (mr *MockIEventCallingMockRecorder) dispatchRecordState(ctx, callID, ctrlID, recordState, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchRecordState", reflect.TypeOf((*MockIEventCalling)(nil).dispatchRecordState), ctx, callID, ctrlID, recordState, rawEvent)
}

// dispatchRecordEventParams mocks base method
func (m *MockIEventCalling) dispatchRecordEventParams(ctx context.Context, callID, ctrlID string, params ParamsEventCallingCallRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchRecordEventParams", ctx, callID, ctrlID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchRecordEventParams indicates an expected call of dispatchRecordEventParams
func (mr *MockIEventCallingMockRecorder) dispatchRecordEventParams(ctx, callID, ctrlID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchRecordEventParams", reflect.TypeOf((*MockIEventCalling)(nil).dispatchRecordEventParams), ctx, callID, ctrlID, params)
}

// dispatchDetect mocks base method
func (m *MockIEventCalling) dispatchDetect(ctx context.Context, callID, ctrlID string, v interface{}, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchDetect", ctx, callID, ctrlID, v, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchDetect indicates an expected call of dispatchDetect
func (mr *MockIEventCallingMockRecorder) dispatchDetect(ctx, callID, ctrlID, v, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchDetect", reflect.TypeOf((*MockIEventCalling)(nil).dispatchDetect), ctx, callID, ctrlID, v, rawEvent)
}

// dispatchFax mocks base method
func (m *MockIEventCalling) dispatchFax(ctx context.Context, callID, ctrlID string, faxType FaxEventType, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchFax", ctx, callID, ctrlID, faxType, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchFax indicates an expected call of dispatchFax
func (mr *MockIEventCallingMockRecorder) dispatchFax(ctx, callID, ctrlID, faxType, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchFax", reflect.TypeOf((*MockIEventCalling)(nil).dispatchFax), ctx, callID, ctrlID, faxType, rawEvent)
}

// dispatchFaxEventParams mocks base method
func (m *MockIEventCalling) dispatchFaxEventParams(ctx context.Context, callID, ctrlID string, params ParamsEventCallingFax) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchFaxEventParams", ctx, callID, ctrlID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchFaxEventParams indicates an expected call of dispatchFaxEventParams
func (mr *MockIEventCallingMockRecorder) dispatchFaxEventParams(ctx, callID, ctrlID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchFaxEventParams", reflect.TypeOf((*MockIEventCalling)(nil).dispatchFaxEventParams), ctx, callID, ctrlID, params)
}

// dispatchTapEventParams mocks base method
func (m *MockIEventCalling) dispatchTapEventParams(ctx context.Context, callID, ctrlID string, params ParamsEventCallingCallTap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchTapEventParams", ctx, callID, ctrlID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchTapEventParams indicates an expected call of dispatchTapEventParams
func (mr *MockIEventCallingMockRecorder) dispatchTapEventParams(ctx, callID, ctrlID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchTapEventParams", reflect.TypeOf((*MockIEventCalling)(nil).dispatchTapEventParams), ctx, callID, ctrlID, params)
}

// dispatchTapState mocks base method
func (m *MockIEventCalling) dispatchTapState(ctx context.Context, callID, ctrlID string, tapState TapState, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchTapState", ctx, callID, ctrlID, tapState, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchTapState indicates an expected call of dispatchTapState
func (mr *MockIEventCallingMockRecorder) dispatchTapState(ctx, callID, ctrlID, tapState, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchTapState", reflect.TypeOf((*MockIEventCalling)(nil).dispatchTapState), ctx, callID, ctrlID, tapState, rawEvent)
}

// dispatchSendDigitsState mocks base method
func (m *MockIEventCalling) dispatchSendDigitsState(ctx context.Context, callID, ctrlID string, sendDigitsState SendDigitsState, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchSendDigitsState", ctx, callID, ctrlID, sendDigitsState, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchSendDigitsState indicates an expected call of dispatchSendDigitsState
func (mr *MockIEventCallingMockRecorder) dispatchSendDigitsState(ctx, callID, ctrlID, sendDigitsState, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchSendDigitsState", reflect.TypeOf((*MockIEventCalling)(nil).dispatchSendDigitsState), ctx, callID, ctrlID, sendDigitsState, rawEvent)
}

// dispatchPlayAndCollectEventParams mocks base method
func (m *MockIEventCalling) dispatchPlayAndCollectEventParams(ctx context.Context, callID, ctrlID string, params ParamsEventCallingCallPlayAndCollect) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchPlayAndCollectEventParams", ctx, callID, ctrlID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchPlayAndCollectEventParams indicates an expected call of dispatchPlayAndCollectEventParams
func (mr *MockIEventCallingMockRecorder) dispatchPlayAndCollectEventParams(ctx, callID, ctrlID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchPlayAndCollectEventParams", reflect.TypeOf((*MockIEventCalling)(nil).dispatchPlayAndCollectEventParams), ctx, callID, ctrlID, params)
}

// dispatchPlayAndCollectResType mocks base method
func (m *MockIEventCalling) dispatchPlayAndCollectResType(ctx context.Context, callID, ctrlID string, resType CollectResultType, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchPlayAndCollectResType", ctx, callID, ctrlID, resType, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchPlayAndCollectResType indicates an expected call of dispatchPlayAndCollectResType
func (mr *MockIEventCallingMockRecorder) dispatchPlayAndCollectResType(ctx, callID, ctrlID, resType, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchPlayAndCollectResType", reflect.TypeOf((*MockIEventCalling)(nil).dispatchPlayAndCollectResType), ctx, callID, ctrlID, resType, rawEvent)
}

// getCall mocks base method
func (m *MockIEventCalling) getCall(ctx context.Context, tag, callID string) (*CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getCall", ctx, tag, callID)
	ret0, _ := ret[0].(*CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCall indicates an expected call of getCall
func (mr *MockIEventCallingMockRecorder) getCall(ctx, tag, callID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCall", reflect.TypeOf((*MockIEventCalling)(nil).getCall), ctx, tag, callID)
}

// getBroadcastParams mocks base method
func (m *MockIEventCalling) getBroadcastParams(ctx context.Context, in, out interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getBroadcastParams", ctx, in, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// getBroadcastParams indicates an expected call of getBroadcastParams
func (mr *MockIEventCallingMockRecorder) getBroadcastParams(ctx, in, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getBroadcastParams", reflect.TypeOf((*MockIEventCalling)(nil).getBroadcastParams), ctx, in, out)
}

// onCallingEventConnect mocks base method
func (m *MockIEventCalling) onCallingEventConnect(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventConnect", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventConnect indicates an expected call of onCallingEventConnect
func (mr *MockIEventCallingMockRecorder) onCallingEventConnect(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventConnect", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventConnect), ctx, broadcast, rawEvent)
}

// onCallingEventReceive mocks base method
func (m *MockIEventCalling) onCallingEventReceive(ctx context.Context, broadcast NotifParamsBladeBroadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventReceive", ctx, broadcast)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventReceive indicates an expected call of onCallingEventReceive
func (mr *MockIEventCallingMockRecorder) onCallingEventReceive(ctx, broadcast interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventReceive", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventReceive), ctx, broadcast)
}

// onCallingEventState mocks base method
func (m *MockIEventCalling) onCallingEventState(ctx context.Context, broadcast NotifParamsBladeBroadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventState", ctx, broadcast)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventState indicates an expected call of onCallingEventState
func (mr *MockIEventCallingMockRecorder) onCallingEventState(ctx, broadcast interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventState", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventState), ctx, broadcast)
}

// onCallingEventPlay mocks base method
func (m *MockIEventCalling) onCallingEventPlay(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventPlay", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventPlay indicates an expected call of onCallingEventPlay
func (mr *MockIEventCallingMockRecorder) onCallingEventPlay(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventPlay", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventPlay), ctx, broadcast, rawEvent)
}

// onCallingEventCollect mocks base method
func (m *MockIEventCalling) onCallingEventCollect(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventCollect", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventCollect indicates an expected call of onCallingEventCollect
func (mr *MockIEventCallingMockRecorder) onCallingEventCollect(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventCollect", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventCollect), ctx, broadcast, rawEvent)
}

// onCallingEventRecord mocks base method
func (m *MockIEventCalling) onCallingEventRecord(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventRecord", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventRecord indicates an expected call of onCallingEventRecord
func (mr *MockIEventCallingMockRecorder) onCallingEventRecord(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventRecord", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventRecord), ctx, broadcast, rawEvent)
}

// onCallingEventTap mocks base method
func (m *MockIEventCalling) onCallingEventTap(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventTap", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventTap indicates an expected call of onCallingEventTap
func (mr *MockIEventCallingMockRecorder) onCallingEventTap(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventTap", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventTap), ctx, broadcast, rawEvent)
}

// onCallingEventDetect mocks base method
func (m *MockIEventCalling) onCallingEventDetect(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventDetect", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventDetect indicates an expected call of onCallingEventDetect
func (mr *MockIEventCallingMockRecorder) onCallingEventDetect(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventDetect", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventDetect), ctx, broadcast, rawEvent)
}

// onCallingEventFax mocks base method
func (m *MockIEventCalling) onCallingEventFax(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventFax", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventFax indicates an expected call of onCallingEventFax
func (mr *MockIEventCallingMockRecorder) onCallingEventFax(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventFax", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventFax), ctx, broadcast, rawEvent)
}

// onCallingEventSendDigits mocks base method
func (m *MockIEventCalling) onCallingEventSendDigits(ctx context.Context, broadcast NotifParamsBladeBroadcast, rawEvent *json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onCallingEventSendDigits", ctx, broadcast, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// onCallingEventSendDigits indicates an expected call of onCallingEventSendDigits
func (mr *MockIEventCallingMockRecorder) onCallingEventSendDigits(ctx, broadcast, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onCallingEventSendDigits", reflect.TypeOf((*MockIEventCalling)(nil).onCallingEventSendDigits), ctx, broadcast, rawEvent)
}

// MockIEventMessaging is a mock of IEventMessaging interface
type MockIEventMessaging struct {
	ctrl     *gomock.Controller
	recorder *MockIEventMessagingMockRecorder
}

// MockIEventMessagingMockRecorder is the mock recorder for MockIEventMessaging
type MockIEventMessagingMockRecorder struct {
	mock *MockIEventMessaging
}

// NewMockIEventMessaging creates a new mock instance
func NewMockIEventMessaging(ctrl *gomock.Controller) *MockIEventMessaging {
	mock := &MockIEventMessaging{ctrl: ctrl}
	mock.recorder = &MockIEventMessagingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEventMessaging) EXPECT() *MockIEventMessagingMockRecorder {
	return m.recorder
}

// onMessagingEventState mocks base method
func (m *MockIEventMessaging) onMessagingEventState(ctx context.Context, broadcast NotifParamsBladeBroadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onMessagingEventState", ctx, broadcast)
	ret0, _ := ret[0].(error)
	return ret0
}

// onMessagingEventState indicates an expected call of onMessagingEventState
func (mr *MockIEventMessagingMockRecorder) onMessagingEventState(ctx, broadcast interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onMessagingEventState", reflect.TypeOf((*MockIEventMessaging)(nil).onMessagingEventState), ctx, broadcast)
}

// dispatchMsgStateNotif mocks base method
func (m *MockIEventMessaging) dispatchMsgStateNotif(ctx context.Context, msgParams MsgParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "dispatchMsgStateNotif", ctx, msgParams)
	ret0, _ := ret[0].(error)
	return ret0
}

// dispatchMsgStateNotif indicates an expected call of dispatchMsgStateNotif
func (mr *MockIEventMessagingMockRecorder) dispatchMsgStateNotif(ctx, msgParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "dispatchMsgStateNotif", reflect.TypeOf((*MockIEventMessaging)(nil).dispatchMsgStateNotif), ctx, msgParams)
}

// msgStateFromStr mocks base method
func (m *MockIEventMessaging) msgStateFromStr(s string) (MsgState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "msgStateFromStr", s)
	ret0, _ := ret[0].(MsgState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// msgStateFromStr indicates an expected call of msgStateFromStr
func (mr *MockIEventMessagingMockRecorder) msgStateFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "msgStateFromStr", reflect.TypeOf((*MockIEventMessaging)(nil).msgStateFromStr), s)
}

// msgDirectionFromStr mocks base method
func (m *MockIEventMessaging) msgDirectionFromStr(s string) (MsgDirection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "msgDirectionFromStr", s)
	ret0, _ := ret[0].(MsgDirection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// msgDirectionFromStr indicates an expected call of msgDirectionFromStr
func (mr *MockIEventMessagingMockRecorder) msgDirectionFromStr(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "msgDirectionFromStr", reflect.TypeOf((*MockIEventMessaging)(nil).msgDirectionFromStr), s)
}

// getMsg mocks base method
func (m *MockIEventMessaging) getMsg(ctx context.Context, msgID string) (*MsgSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getMsg", ctx, msgID)
	ret0, _ := ret[0].(*MsgSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getMsg indicates an expected call of getMsg
func (mr *MockIEventMessagingMockRecorder) getMsg(ctx, msgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getMsg", reflect.TypeOf((*MockIEventMessaging)(nil).getMsg), ctx, msgID)
}

// MockIEventTasking is a mock of IEventTasking interface
type MockIEventTasking struct {
	ctrl     *gomock.Controller
	recorder *MockIEventTaskingMockRecorder
}

// MockIEventTaskingMockRecorder is the mock recorder for MockIEventTasking
type MockIEventTaskingMockRecorder struct {
	mock *MockIEventTasking
}

// NewMockIEventTasking creates a new mock instance
func NewMockIEventTasking(ctrl *gomock.Controller) *MockIEventTasking {
	mock := &MockIEventTasking{ctrl: ctrl}
	mock.recorder = &MockIEventTaskingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEventTasking) EXPECT() *MockIEventTaskingMockRecorder {
	return m.recorder
}

// onTaskingEvent mocks base method
func (m *MockIEventTasking) onTaskingEvent(ctx context.Context, broadcast NotifParamsBladeBroadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "onTaskingEvent", ctx, broadcast)
	ret0, _ := ret[0].(error)
	return ret0
}

// onTaskingEvent indicates an expected call of onTaskingEvent
func (mr *MockIEventTaskingMockRecorder) onTaskingEvent(ctx, broadcast interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onTaskingEvent", reflect.TypeOf((*MockIEventTasking)(nil).onTaskingEvent), ctx, broadcast)
}
