kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test-go1.12
  image: golang:1.12
  commands:
  - apt-get -qq update
  - apt-get -y install build-essential pkg-config libopus-dev libopusfile-dev
  - make update
  - make linter-install
  - make test
  - make lint

#- name: test-go1.11
#  image: golang:1.11
#  commands:
#  - find -name go.mod -exec sed -i 's/go 1.12/go 1.11/g' {} \;
#  - make update
#  - make linter-install
#  - make test
#  - make lint

trigger:
  event: push
