kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.11
  commands:
  - make update
  - make linter-install
  - make test
  - make lint

trigger:
  event: push
